version: '2.1'
services:
  ### Nginx Web Container #######################################
  nginx:
    build: ./nginx
    container_name: lnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    #source code container
    volumes_from:
      - www
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/socket:/var/run
    links:
      - php-fpm:php-fpm
    extra_hosts:
      - "${DOMAIN}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN2}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN3}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN4}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN5}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN6}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN7}:${NGINX_WEB_SERVER_IP}"
    networks:
      web_server_network:
        ipv4_address: ${NGINX_WEB_SERVER_IP}

  ### PHP-FPM Container #######################################
  php-fpm:
    build: ./php-fpm
    container_name: lnmp-php-fpm
      #source code container
    volumes_from:
      - www
    volumes:
      - ./nginx/logs/php-fpm:/usr/local/var/log/php7
      - ./nginx/socket:/var/run
    links:
      - mysql
      - redis
    #https://github.com/laradock/laradock/issues/435
    extra_hosts:
      - "${DOMAIN}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN2}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN3}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN4}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN5}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN6}:${NGINX_WEB_SERVER_IP}"
      - "${DOMAIN7}:${NGINX_WEB_SERVER_IP}"
    env_file:
      - .env
    networks:
      - web_server_network

  ### MySQL Container #######################################
  # MySQL - One of the most popular database servers. Made by the original developers of MySQL. Guaranteed to stay open source.
  mysql:
    image: mysql:8.0.22
    container_name: lnmp-mysql
    ports:
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
    networks:
      - web_server_network

  ### REDIS Container #######################################
  redis:
    build: ./redis
    container_name: lnmp-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    environment:
      - REDIS_PASSWORD=developer
    networks:
      - web_server_network

  ### Web-Root Container #######################################
  www:
    image: tianon/true
    container_name: lnmp-www
    volumes:
      - ./www:/data/www
      - ./logs:/data/reachmax_logs

### Networks Setup ############################################
networks:
  web_server_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "${WEB_SERVER_SUBNET}"
        gateway: "${WEB_SERVER_GATEWAY}"
